In [1]:
import sys

In [2]:
sys.path.append("src")

In [3]:
import stocks

2026-03-15 12:18:28.712 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [4]:
stocks.get_stock_data("AAPL")

2026-03-15 12:18:34.513 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-03-15 12:18:34.516 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-03-14 00:00:00-04:00,149.119690,151.209411,147.956548,150.410980,73695900,0.0,0.0
2023-03-15 00:00:00-04:00,149.030984,151.061564,147.779115,150.805283,77167900,0.0,0.0
2023-03-16 00:00:00-04:00,149.987097,154.225694,149.474519,153.624405,76161100,0.0,0.0
2023-03-17 00:00:00-04:00,153.851139,154.501718,152.076841,152.786560,98944600,0.0,0.0
2023-03-20 00:00:00-04:00,152.855584,155.566314,151.948708,155.152298,73641400,0.0,0.0
...,...,...,...,...,...,...,...
2026-03-09 00:00:00-04:00,255.690002,261.149994,253.679993,259.880005,38218500,0.0,0.0
2026-03-10 00:00:00-04:00,257.649994,262.480011,256.950012,260.829987,30590800,0.0,0.0
2026-03-11 00:00:00-04:00,261.089996,262.130005,259.549988,260.809998,26218900,0.0,0.0
2026-03-12 00:00:00-04:00,258.660004,258.950012,254.179993,255.759995,40794000,0.0,0.0
2026-03-13 00:00:00-04:00,255.399994,256.329987,249.520004,250.119995,34193754,0.0,0.0

In [6]:
import yfinance as yf

In [9]:
aapl = yf.Ticker("AAPL")

In [10]:
aapl.quarterly_financials

,2025-12-31,2025-09-30,2025-06-30,2025-03-31,2024-12-31
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Tax Rate For Calcs,1.750000e-01,1.627240e-01,1.640000e-01,1.550000e-01,1.470000e-01
Normalized EBITDA,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10
Net Income From Continuing Operation Net Minority Interest,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Reconciled Depreciation,3.214000e+09,3.127000e+09,2.830000e+09,2.661000e+09,3.080000e+09
Reconciled Cost Of Revenue,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10,6.602500e+10
EBITDA,5.406600e+10,3.555400e+10,3.103200e+10,3.225000e+10,4.591200e+10
EBIT,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Normalized Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income From Continuing And Discontinued Operation,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Total Expenses,9.290400e+10,7.003900e+10,6.583400e+10,6.577000e+10,8.146800e+10
Total Operating Income As Reported,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Diluted Average Shares,1.481036e+10,1.486361e+10,1.494818e+10,1.505613e+10,1.515086e+10
Basic Average Shares,1.474816e+10,1.481531e+10,1.490289e+10,1.499408e+10,1.508172e+10
Diluted EPS,2.840000e+00,1.850000e+00,1.570000e+00,1.650000e+00,2.400000e+00
Basic EPS,2.850000e+00,1.850000e+00,1.570000e+00,1.650000e+00,2.410000e+00
Diluted NI Availto Com Stockholders,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income Common Stockholders,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income Including Noncontrolling Interests,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Net Income Continuous Operations,4.209700e+10,2.746600e+10,2.343400e+10,2.478000e+10,3.633000e+10
Tax Provision,8.905000e+09,5.338000e+09,4.597000e+09,4.530000e+09,6.254000e+09
Pretax Income,5.100200e+10,3.280400e+10,2.803100e+10,2.931000e+10,4.258400e+10
Other Income Expense,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08,-2.480000e+08
Other Non Operating Income Expenses,1.500000e+08,3.770000e+08,-1.710000e+08,-2.790000e+08,-2.480000e+08
Operating Income,5.085200e+10,3.242700e+10,2.820200e+10,2.958900e+10,4.283200e+10
Operating Expense,1.837900e+10,1.591400e+10,1.551600e+10,1.527800e+10,1.544300e+10
Research And Development,1.088700e+10,8.866000e+09,8.866000e+09,8.550000e+09,8.268000e+09
Selling General And Administration,7.492000e+09,7.048000e+09,6.650000e+09,6.728000e+09,7.175000e+09
Gross Profit,6.923100e+10,4.834100e+10,4.371800e+10,4.486700e+10,5.827500e+10
Cost Of Revenue,7.452500e+10,5.412500e+10,5.031800e+10,5.049200e+10,6.602500e+10
Total Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11
Operating Revenue,1.437560e+11,1.024660e+11,9.403600e+10,9.535900e+10,1.243000e+11

In [11]:
aapl.earnings_history

            epsActual  epsEstimate  epsDifference  surprisePercent
quarter
2025-03-31       1.65      1.62253           0.03           0.0169
2025-06-30       1.57      1.42572           0.14           0.1012
2025-09-30       1.85      1.76993           0.08           0.0452
2025-12-31       2.84      2.67080           0.17           0.0634

In [13]:
aapl.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 150000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP of Government Affairs & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Jennifer G. Newstead J.D.',
   'age': 54,
   'title': 'Senior VP & General Counsel',
   'yearBorn': 1971,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 1,
 'compensationRisk': 7,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1772323200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 255.76,
 'open': 255.4,
 'dayLow': 249.52,
 'dayHigh': 256.33,
 'regularMarketPreviousClose': 255.76,
 'regularMarketOpen': 255.4,
 'regularMarketDayLow': 249.52,
 'regularMarketDayHigh': 256.33,
 'dividendRate': 1.04,
 'dividendYield': 0.42,
 'exDividendDate': 1770595200,
 'payoutRatio': 0.1304,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.116,
 'trailingPE': 31.660759,
 'forwardPE': 26.906572,
 'volume': 34193754,
 'regularMarketVolume': 34193754,
 'averageVolume': 47924558,
 'averageVolume10days': 38369060,
 'averageDailyVolume10Day': 38369060,
 'bid': 240.0,
 'ask': 250.65,
 'bidSize': 1,
 'askSize': 3,
 'marketCap': 3676245065728,
 'nonDilutedMarketCap': 3672046736800,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 8.439168,
 'fiftyDayAverage': 262.7076,
 'twoHundredDayAverage': 245.5843,
 'trailingAnnualDividendRate': 1.03,
 'trailingAnnualDividendYield': 0.004027213,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3695648702464,
 'profitMargins': 0.27037,
 'floatShares': 14656182062,
 'sharesOutstanding': 14681140000,
 'sharesShort': 129553812,
 'sharesShortPriorMonth': 116854414,
 'sharesShortPreviousMonthDate': 1769731200,
 'dateShortInterest': 1772150400,
 'sharesPercentSharesOut': 0.0088,
 'heldPercentInsiders': 0.01637,
 'heldPercentInstitutions': 0.65262,
 'shortRatio': 2.41,
 'shortPercentOfFloat': 0.0088,
 'impliedSharesOutstanding': 14697926000,
 'bookValue': 5.998,
 'priceToBook': 41.700565,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1766793600,
 'earningsQuarterlyGrowth': 0.159,
 'netIncomeToCommon': 117776998400,
 'trailingEps': 7.9,
 'forwardEps': 9.29587,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.484,
 'enterpriseToEbitda': 24.17,
 '52WeekChange': 0.1687851,
 'SandP52WeekChange': 0.16864312,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1770595200,
 'quoteType': 'EQUITY',
 'currentPrice': 250.12,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 295.43536,
 'targetMedianPrice': 300.0,
 'recommendationMean': 1.89583,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 66907000832,
 'totalCashPerShare': 4.557,
 'ebitda': 152901992448,
 'totalDebt': 90509000704,
 'quickRatio': 0.845,
 'currentRatio': 0.974,
 'totalRevenue': 435617005568,
 'debtToEquity': 102.63,
 'revenuePerShare': 29.305,
 'returnOnAssets': 0.24377,
 'returnOnEquity': 1.5202099,
 'grossProfits': 206157004800,
 'freeCashflow': 106312753152,
 'operatingCashflow': 135471996928,
 'earningsGrowth': 0.183,
 'revenueGrowth': 0.157,
 'grossMargins': 0.47325,
 'ebitdaMargins': 0.35099998,
 'operatingMargins': 0.35374,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'corporateActions': [],
 'postMarketTime': 1773446398,
 'regularMarketTime': 1773432003,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'postMarketChangePercent': -0.11993755,
 'postMarketPrice': 249.82,
 'postMarketChange': -0.2999878,
 'regularMarketChange': -5.64,
 'regularMarketDayRange': '249.52 - 256.33',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 47924558,
 'fiftyTwoWeekLowChange': 80.90999,
 'fiftyTwoWeekLowChangePercent': 0.47816315,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -38.5,
 'fiftyTwoWeekHighChangePercent': -0.13339339,
 'fiftyTwoWeekChangePercent': 16.87851,
 'dividendDate': 1770854400,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1777579200,
 'earningsTimestampEnd': 1777579200,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': True,
 'epsTrailingTwelveMonths': 7.9,
 'epsForward': 9.29587,
 'epsCurrentYear': 8.51111,
 'priceEpsCurrentYear': 29.38747,
 'fiftyDayAverageChange': -12.587616,
 'fiftyDayAverageChangePercent': -0.047914926,
 'twoHundredDayAverageChange': 4.5356903,
 'twoHundredDayAverageChangePercent': 0.018468974,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'regularMarketChangePercent': -2.20519,
 'regularMarketPrice': 250.12,
 'averageAnalystRating': '1.9 - Buy',
 'cryptoTradeable': False,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'displayName': 'Apple',
 'trailingPegRatio': 2.2387}